### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by dtcarls** [joeyagreco/sleeper#34]
I copy pasted your league example and tried to run it and couldn't properly import. I am using the latest pypi sleeper package (1.3.0) and python 3.9.6. Am I doing something blatantly wrong or miss an instruction somewhere?

$ python3 tests/sleeper_api.py 
```
Traceback (most recent call last):
  File "/Users/test/Documents/dev/test_sleeper_api/tests/sleeper_api.py", line 1, in <module>
    from sleeper.api import LeagueAPIClient
  File "/Users/test/Documents/dev/test_sleeper_api/.venv/lib/python3.9/site-packages/sleeper/api/__init__.py", line 1, in <module>
    from .AvatarAPIClient import AvatarAPIClient
  File "/Users/test/Documents/dev/test_sleeper_api/.venv/lib/python3.9/site-packages/sleeper/api/AvatarAPIClient.py", line 1, in <module>
    from sleeper.api.SleeperAPIClient import SleeperAPIClient
  File "/Users/test/Documents/dev/test_sleeper_api/.venv/lib/python3.9/site-packages/sleeper/api/SleeperAPIClient.py", line 12, in <module>
    class SleeperAPIClient(ABC):
  File "/Users/test/Documents/dev/test_sleeper_api/.venv/lib/python3.9/site-packages/sleeper/api/SleeperAPIClient.py", line 71, in SleeperAPIClient
    def _get(url: str) -> Optional[dict | list]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by dtcarls** [comment]
After looking at the badges on the readme, it requires python 3.10+. My dumb mistake.
